Vagrant.configure("2") do |config|
  config.vm.define "doc1" do |doc1|
    doc1.vm.box = "ubuntu/focal64"
    doc1.vm.network "public_network", ip: "192.168.50.51"
    doc1.vm.hostname = "doc1"
    doc1.vm.provider "virtualbox" do |vb|
      vb.name = "doc1"
      vb.memory = "12288"
			vb.cpus = 8
    end
		doc1.vm.provision "file", source: "./vault_jenkins", destination: "/tmp/vault_jenkins"
		doc1.vm.provision "shell", path: "bootstrap.sh"
  end
end
