Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  N = 3
  (1..N).each do |i|
    config.vm.define "kuber-#{25+i}" do |vm|
      vm.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9560 160MHz", ip: "192.168.50.#{25+i}"
      vm.vm.hostname = "kuber-#{25+i}"
      vm.vm.provider "virtualbox" do |vb|
        vb.name = "kuber-#{25+i}"
        vb.memory = "1024"
      end
    end
  end
end
