groups:
  - name: basic
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Target down"
          description: "Instance {{ $labels.instance }} (job={{ $labels.job }}) is down"